// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwC3Sw8lHmUJlAf6NT6jJEsc2F9LECL68',
    appId: '1:382596631008:web:6c3e90576a638a4e4f4385',
    messagingSenderId: '382596631008',
    projectId: 'chhotokhabar-27341',
    authDomain: 'chhotokhabar-27341.firebaseapp.com',
    storageBucket: 'chhotokhabar-27341.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVSpGpv1VMJ2sSfO-kNjCSuQbm-7s37s',
    appId: '1:382596631008:android:9c9d51c409b9c42a4f4385',
    messagingSenderId: '382596631008',
    projectId: 'chhotokhabar-27341',
    storageBucket: 'chhotokhabar-27341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwimkttQC4_ki97J1froIpzXKA_-UptE',
    appId: '1:382596631008:ios:87177c5d0732f6504f4385',
    messagingSenderId: '382596631008',
    projectId: 'chhotokhabar-27341',
    storageBucket: 'chhotokhabar-27341.firebasestorage.app',
    iosBundleId: 'com.example.chhotoKhabar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwimkttQC4_ki97J1froIpzXKA_-UptE',
    appId: '1:382596631008:ios:87177c5d0732f6504f4385',
    messagingSenderId: '382596631008',
    projectId: 'chhotokhabar-27341',
    storageBucket: 'chhotokhabar-27341.firebasestorage.app',
    iosBundleId: 'com.example.chhotoKhabar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwC3Sw8lHmUJlAf6NT6jJEsc2F9LECL68',
    appId: '1:382596631008:web:ee490371676f9b444f4385',
    messagingSenderId: '382596631008',
    projectId: 'chhotokhabar-27341',
    authDomain: 'chhotokhabar-27341.firebaseapp.com',
    storageBucket: 'chhotokhabar-27341.firebasestorage.app',
  );
}
